### ISSUE TITLE
ERROR Cannot load adapter messenger-bot - Error: Cannot find module 'hubot' from parent

### ISSUE THREAD

**Issue by chrispanag** [ClaudeBot/hubot-messenger-bot#1]
On a fresh install of hubot after installing this module, upon running the bot via `./bin/hubot -a messenger-bot` the above error happens.

**Comment by MrSaints** [comment]
Have you tried removing `node_modules`, and re-running `npm install` ?

**Comment by chrispanag** [comment]
Just did that, unfortunately it persists with the same error

**Comment by MrSaints** [comment]
Hmm, if you don't mind, can you share the contents of your `package.json`? 

It might also be related to the version of Hubot. Are other adapters working as expected?

**Comment by chrispanag** [comment]
This is my package.json, thanks for your help :) 

```
{
  "name": "hubot",
  "version": "2.18.0",
  "author": "hubot",
  "keywords": [
    "github",
    "hubot",
    "campfire",
    "bot"
  ],
  "description": "A simple helpful robot for your Company",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/github/hubot.git"
  },
  "dependencies": {
    "async": ">=0.1.0 <1.0.0",
    "chalk": "^1.0.0",
    "cline": "^0.8.2",
    "coffee-script": "1.6.3",
    "connect-multiparty": "^1.2.5",
    "express": "^3.21.2",
    "hubot-messenger-bot": "^1.0.1",
    "log": "1.4.0",
    "optparse": "1.0.4",
    "scoped-http-client": "0.11.0",
    "hubot-messenger-bot": "*"
  },
  "devDependencies": {
    "hubot-mock-adapter": "^1.0.0",
    "coffee-errors": "0.8.6",
    "mocha": "^2.1.0",
    "mockery": "^1.4.0",
    "sinon-chai": "^2.8.0",
    "sinon": "~1.17.0",
    "chai": "~2.1.0"
  },
  "engines": {
    "node": ">= 0.8.x",
    "npm": ">= 1.1.x"
  },
  "main": "./index",
  "bin": {
    "hubot": "./bin/hubot"
  },
  "scripts": {
    "test": "./script/test"
  }
}

```

**Comment by MrSaints** [comment]
@chrispanag no worries. Always happy to help :smile:

From the looks of it, you are running Hubot straight from the `github/hubot` repository. 
Unfortunately, that will not work. You'll have to create an "instance" of Hubot. The easiest way is through Yeoman: https://hubot.github.com/docs/

Let me know how it goes.

**Comment by chrispanag** [comment]
Thank you very much! 
Anyways, keep up to the great (and very timely) work!
