### ISSUE TITLE
404 on webhook URL?

### ISSUE THREAD

**Issue by sapg** [ClaudeBot/hubot-messenger-bot#2]
I've tried with ngrok as you suggested in the readme but I get a 404.

ngrok by @inconshreveable                                                                                          (Ctrl+C to quit)

Tunnel Status                 online  
Version                       2.0.25/2.0.25  
Region                        United States (us)  
Web Interface                 http://127.0.0.1:4040  
Forwarding                    http://1d35d110.ngrok.io -> localhost:8080  
Forwarding                    https://1d35d110.ngrok.io -> localhost:8080                                                          

Connections                   ttl     opn     rt1     rt5     p50     p90  
                              2       0       0.00    0.00    0.09    0.10                                                         
## HTTP Requests                                                                                                                      

GET /webhook                   404 Not Found  
GET /webhook                   404 Not Found                                                                                       

hubot is running with your adapter, there are no errors on startup.  What could I be missing?

my-bot# ./bin/hubot -a messenger-bot
[Thu Apr 14 2016 17:44:55 GMT+0300 (MSK)] INFO hubot-messenger-bot: Adapter loaded.
[Thu Apr 14 2016 17:44:55 GMT+0300 (MSK)] INFO hubot-messenger-bot: Adapter running.
[Thu Apr 14 2016 17:44:56 GMT+0300 (MSK)] INFO Data for hubot brain retrieved from Redis

**Comment by MrSaints** [comment]
It's `/webhook/` with the trailing slash @sapg

**Comment by sapg** [comment]
Ah, excellent.  Thanks very much.

**Comment by MrSaints** [comment]
You're welcome :smile: @sapg 

Let me know if you run into any other issues.

**Comment by Anders123** [comment]
No comment. Mistake.
