### ISSUE TITLE
Info: Extra Step I Needed

### ISSUE THREAD

**Issue by sapg** [ClaudeBot/hubot-messenger-bot#3]
This is information rather than an issue.  After I did my webhook config I then needed to do this on the machine where I was running hubot for it to start replying.

curl -ik -X POST "https://graph.facebook.com/v2.6/me/subscribed_apps?access_token=<page access toke>"

**Comment by MrSaints** [comment]
@sapg, yea, I was being lazy with the documentation. I'll update it to reflect the individual steps. Thank you :smile:
